#!/usr/bin/env python3
"""pidash brand mark (asset A1 of docs/design-improvement-plan.md). One geometry, every file, plus the checks.

    python3 docs/images/src/mark/build.py [OUT]     # OUT defaults to frontend/public

Writes the web set (favicon.svg, favicon-warn.svg, favicon-bad.svg, favicon-off.svg, icon.svg, icon-192.png, icon-512.png,
apple-touch-icon.png) to OUT, the inline header SVG to header-mark.svg next to this file, and the README copy to
docs/images/mark.svg. Needs rsvg-convert and Pillow.

The grid is 32 units: at 16 px one pixel is 2 units, so fills sit on even units and 2-unit strokes on odd centre lines.
The favicon renders with crispEdges, which turns each 45-degree line into a clean one-pixel staircase at 16 px.
"""
import subprocess
import sys
import tempfile
from pathlib import Path

from PIL import Image

HERE = Path(__file__).resolve().parent
OUT = Path(sys.argv[1]) if len(sys.argv) > 1 else HERE.parents[3] / 'frontend' / 'public'
README_MARK = HERE.parents[1] / 'mark.svg'

MASK, GOLD, AMBER, RED, OFF = '#0b1712', '#d9b35d', '#ffb93e', '#ff5f55', '#52635a'
# Pin-1 chamfer. 8.5, not 8: no pixel centre sits on the cut at 16 or 32 px, so crisp renderers never have to guess.
TILE = f'<path d="M8.5 0H32V32H0V8.5Z" fill="{MASK}"/>'


def art(c):
    """The board in one colour: chamfered outline, 4 GPIO pads, the SoC left of centre, and two 45-degree traces,
    one off the SoC's top edge to pad 2 and one off its right edge to pad 4, so at 16 px the SoC stays a clean square
    and all 4 pads stay countable."""
    return (
        f'<path d="M7 5H29V27H3V9Z" fill="none" stroke="{c}" stroke-width="2"/>'
        f'<path d="M11 16V15L15 11V10M14 19H15L23 11V10" fill="none" stroke="{c}" stroke-width="2"/>'
        f'<path d="M10 8h2v2h-2zM14 8h2v2h-2zM18 8h2v2h-2zM22 8h2v2h-2zM6 16h8v8H6z" fill="{c}"/>'
    )


def svg(body, box='0 0 32 32', extra=''):
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{box}"{extra}>'
            f'<!-- generated by docs/images/src/mark/build.py -->{body}</svg>\n')


def led(color):
    # plan item M8: the tab icon carries the worst health state as an LED lens, on a mask ring, at the lower right
    return f'<circle cx="25" cy="25" r="6" fill="{MASK}"/><circle cx="25" cy="25" r="4.5" fill="{color}"/>'


CRISP = f'<g shape-rendering="crispEdges">{TILE}{art(GOLD)}</g>'
FILES = {
    'favicon.svg': svg(CRISP),
    'favicon-warn.svg': svg(CRISP + led(AMBER)),
    'favicon-bad.svg': svg(CRISP + led(RED)),
    'favicon-off.svg': svg(CRISP + led(OFF)),
    # full bleed for maskable use: the art scaled 11x about the centre stays inside the 80 % safe circle
    'icon.svg': svg(f'<rect width="512" height="512" fill="{MASK}"/>'
                    f'<g transform="translate(256 256) scale(11) translate(-16 -16)">{art(GOLD)}</g>', '0 0 512 512'),
}
# inline in index.html's header, on the same 24-unit viewBox as the Lucide icons
HEADER = svg(f'<g transform="scale(.75)">{art("currentColor")}</g>', '0 0 24 24', ' class="brand-mark" aria-hidden="true"')


def render(src, px, dst):
    subprocess.run(['rsvg-convert', '-w', str(px), '-h', str(px), str(src), '-o', str(dst)], check=True)
    Image.open(dst).save(dst, optimize=True)


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    for name, text in FILES.items():
        (OUT / name).write_text(text)
    (HERE / 'header-mark.svg').write_text(HEADER)
    README_MARK.write_text(svg(TILE + art(GOLD)))  # smooth edges: GitHub shows it at 88 px
    for name, px in (('icon-192.png', 192), ('icon-512.png', 512), ('apple-touch-icon.png', 180)):
        render(OUT / 'icon.svg', px, OUT / name)

    # checks
    with tempfile.TemporaryDirectory() as tmp:
        allowed = {tuple(int(h[i:i + 2], 16) for i in (1, 3, 5)) for h in (MASK, GOLD)}
        for px in (16, 32):
            render(OUT / 'favicon.svg', px, Path(tmp) / 'f.png')
            im = Image.open(Path(tmp) / 'f.png').convert('RGBA')
            soft = sum(1 for p in im.get_flattened_data() if p[3] != 0 and not (p[3] == 255 and p[:3] in allowed))
            print(f'favicon {px} px: {soft} anti-aliased pixels')
            assert soft <= 10, 'the plan allows at most 10 at 16 px'
    im = Image.open(OUT / 'icon-512.png').convert('RGB')
    outside = sum(1 for y in range(512) for x in range(512)
                  if (x + .5 - 256) ** 2 + (y + .5 - 256) ** 2 > 204.8 ** 2 and im.getpixel((x, y)) != (11, 23, 18))
    print(f'icon-512: {outside} px outside the 80 % safe circle')
    assert outside == 0
    assert Image.open(OUT / 'apple-touch-icon.png').convert('RGBA').getextrema()[3][0] == 255, 'must be opaque'
    index = HERE.parents[3] / 'frontend' / 'index.html'
    assert HEADER.strip() in index.read_text(), f'paste {HERE / "header-mark.svg"} over the .brand-mark svg in {index}'
    for f in sorted(OUT.iterdir()):
        print(f'{f.stat().st_size:>7} B  {f}')
    for f in (HERE / 'header-mark.svg', README_MARK):
        print(f'{f.stat().st_size:>7} B  {f}')


if __name__ == '__main__':
    main()
